from __future__ import annotations

import re

from client.responses.base import Response
from client.manager.group import Group
from client.manager.member import Member

class EssayBotDetectResponse(Response):
  name = "essay_bot_detect"
  description = "Detects if a message is likely generated by an essay bot"
  priority = 15
  targets = [
    re.compile(r"https?://(?:(?:speedy|e?x(?:tra|))-?essay(?:[sz]|service|)|paper(?:ok|[cgsz]))\.(?:cf|ml|ga|gq)", re.MULTILINE | re.IGNORECASE)
  ]

  def execute(self, message, context):
    group = Group(group_id=context.group_id, token=context.token)

    sender_user_id = str(context.sender_id or "").strip()
    sender_membership_id = ""
    for member in group.get_members():
      member_user_id = str(member.get("user_id") or member.get("id") or "").strip()
      if member_user_id == sender_user_id:
        sender_membership_id = str(member.get("id") or "").strip()
        break

    if not sender_membership_id:
      return (
        f"Detected a potential essay bot from {context.sender_name}. "
        "Could not resolve the member record to kick."
      )

    sender = Member(id=sender_membership_id, group=group, token=context.token)

    try:
      if context.message_id:
        group.delete_message(context.message_id)
      sender.kick()
    except Exception as e:
      return f"Detected a potential essay bot from {context.sender_name}. Failed to kick the member: {str(e)}"
    
    return f"Detected a potential essay bot from {context.sender_name}. The member has been kicked from the group."